In [2]:
import numpy as np

In [9]:
a = np.arange(0, 10)
b = np.arange(0, 20, 2)

In [10]:
print(a)
print(b)
print(a+b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]


In [6]:
a = a.reshape(2,5)
b = b.reshape(2,5)
print(a)
print(b)
print(a*b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[  0   2   8  18  32]
 [ 50  72  98 128 162]]


In [52]:
print(a[1,3])
print(a[0,:])
print(b[:,0])
print(a[-1])

8
[0 1 2 3 4]
[ 0 10]
[5 6 7 8 9]


In [51]:
c = np.random.randint(0,40, [2,5,4])
print(c)
print(c - 39) # broadcast scalar 39 to shape [2,5,4]
print(c + np.array([1,2,3,4])) # broadcast tensor [1,2,3,4] to shape [2,5,4]

[[[ 5  8 36 24]
  [38 36  9  7]
  [37 30  4  4]
  [ 4  1 15 12]
  [ 0 31 28 24]]

 [[18 20 23  1]
  [ 9 13 37 31]
  [21  8 17 19]
  [14  4 11  9]
  [10  7 11 26]]]
[[[-34 -31  -3 -15]
  [ -1  -3 -30 -32]
  [ -2  -9 -35 -35]
  [-35 -38 -24 -27]
  [-39  -8 -11 -15]]

 [[-21 -19 -16 -38]
  [-30 -26  -2  -8]
  [-18 -31 -22 -20]
  [-25 -35 -28 -30]
  [-29 -32 -28 -13]]]
[[[ 6 10 39 28]
  [39 38 12 11]
  [38 32  7  8]
  [ 5  3 18 16]
  [ 1 33 31 28]]

 [[19 22 26  5]
  [10 15 40 35]
  [22 10 20 23]
  [15  6 14 13]
  [11  9 14 30]]]


In [49]:
print((c >= 20) * np.random.randint(0,40,c.shape))

[[[ 0  0  0  0]
  [ 0 35  0  0]
  [18 36  0  0]
  [ 0 20  0  0]
  [ 0  5 37  0]]

 [[31  0  0  1]
  [12  0  0 34]
  [ 0  0 37 11]
  [27  0 29  7]
  [ 9  0  0 21]]]
